### ISSUE TITLE
New mod builds for older MC versions?

### ISSUE THREAD

**Issue by hazylua** [quinn-semele/expanded-storage#14]
I'm using the mod on a 1.19.2 modpack and was wondering if there are any plans on having new builds for this version, since there are fixes from the newer versions of the mod that I'm interested in.

Thank you for the mod in any case, I'm enjoying it a lot.

**Comment by quinn-semele** [comment]
Yeah that should be possible, might take a few days but I'll get started on it now, hopefully I haven't changed too much

**Comment by hazylua** [comment]
> Heyo, just finished what should be a complete backport, is the mod pack you are using public, I'd just like to quickly test any mods with compatibility to ensure I've not broken anything.

I'm using Raspberry Flavored and just added your chest mod alongside it out of curiosity, so it's not native to the modpack itself. IIRC the main checks for compat would be with Create and whatever chest filter/sort functions the pack has added to it.

**Comment by quinn-semele** [comment]
I have released a backport here, if anything is broken please report it to me, sorry for the delay!

https://modrinth.com/mod/expanded-storage/version/8.4.0-beta.1+forge
