### ISSUE TITLE
[1.21] [Neoforge] update to breaking neoforge changes 

### ISSUE THREAD

**Issue by ffuentesm** [quinn-semele/expanded-storage#16]
![image](https://github.com/quinn-semele/expanded-storage/assets/44974827/8a9958c1-4077-4c54-acd5-40d0623105af)
Neoforge: 21.0.40
Expanded Storage: 14.0.0
Log: https://pastebin.com/yWZbYGfW

**Comment by Gbergz** [comment]
Came to report the same thing, glad it is already.

Though, is this fix being published?

**Comment by Periam** [comment]
the issue is still present on expandedstorage-14.0.0+1.21-forge

**Comment by quinn-semele** [comment]
Sorry I've been away from modding for a while, going to get back into the groove and fix this first.

**Comment by Gbergz** [comment]
Awesome, no worries!

**Comment by quinn-semele** [comment]
Seems like Andromeda/3x1t-5tyl3 already fixed it for me, just pushing a release now ^_^

**Comment by quinn-semele** [comment]
**Expanded Storage 14.0.1** for **1.21**
- Fix NeoForge release for builds past 21.0.40, thanks to [Andromeda/3x1t-5tyl3](<https://github.com/3x1t-5tyl3>) for this fix!

CurseForge: [NeoForge](<https://curseforge.com/minecraft/mc-mods/expanded-storage/files/5514420>)
Modrinth: [NeoForge](<https://modrinth.com/mod/jCCPlP3c/version/UHDjGFBK>)

**Comment by Gbergz** [comment]
Thank you, appreciated!
