### ISSUE TITLE
I think there's an issue with this mod and Quark

### ISSUE THREAD

**Issue by Greg727** [quinn-semele/expanded-storage#2]
I was loading my world with this mod along with the Quark mod, but my game crashed.

Crash Report:  crash-2024-02-27_16.08.08-fml.txt](https://github.com/quinn-semele/expanded-storage/files/14425750/crash-2024-02-27_16.08.08-fml.txt)

**Comment by WimpieRatte** [comment]
yeah - I'm getting the following error in a crash screen when the game loads:
"Expanded Storage (expandedstorage) encountered an error during the sided_setup event phase
java.lang.NoClassDefFoundError: vazkii/quark/api/IQuarkButtonAllowed"

**Comment by quinn-semele** [comment]
Fixed, sorry about that:

https://modrinth.com/mod/expanded-storage/version/DN5CtCJQ
https://www.curseforge.com/minecraft/mc-mods/expanded-storage/files/5142884

**Comment by WimpieRatte** [comment]
awesome!! thank you, dude!
Was so glad when I saw this mod releasing now for 1.20.1 Forge.
Was very easy for me to make the switch decision :D.
