### ISSUE TITLE
Add capabilities to transfer items to carts

### ISSUE THREAD

**Issue by Edivad99** [quinn-semele/expanded-storage#20]
Hi, I'm one of the railcraft developers.
We recently received a [request](https://github.com/railcraft-reborn/railcraft/issues/227) to make the railcraft item loaders/unloaders compatible with the carts added by your mod.
I just debugged why it doesn't work and it seems like you don't expose the capabilities to transfer items.
If you can add this capability it would be great
![Screenshot 2024-07-23 alle 20 09 57](https://github.com/user-attachments/assets/73ce2e9d-db80-44f8-a8f3-3f346f86c118)
![Screenshot 2024-07-23 alle 20 10 06](https://github.com/user-attachments/assets/dc2be40e-3d39-40be-b30f-192490857509)

**Comment by quinn-semele** [comment]
I honestly had no clue there was capabilities for entities... I'll get on that soon, thanks for bringing that to my attention

**Comment by Edivad99** [comment]
@quinn-semele I posted a comment [here](https://github.com/quinn-semele/expanded-storage/commit/6e160d45225afdeb56f89d45a27d09a11b8d9e79#r144749036)

**Comment by quinn-semele** [comment]
Thank you, sorry been a little busy chatting in a discord xD, will quickly ammend that and see how much of a 1.20.1 backport I can get done today, I don't think too much has changed so it should be pretty quick.

**Comment by Rundas01** [comment]
Thanks for your efforts
