### ISSUE TITLE
Question about reinstalling the mod

### ISSUE THREAD

**Issue by barisyild** [quinn-semele/expanded-storage#21]
When uninstall the mod, load the world and reinstall the mod, the chest doesn't come back in the world.

Is there any way to get the lost items back?

**Comment by quinn-semele** [comment]
Honestly unless you kept a back up the answer is no, removing mods e.g. loading a modded save in vanilla, is inherently destructive.

**Comment by barisyild** [comment]
> Honestly unless you kept a back up the answer is no, removing mods e.g. loading a modded save in vanilla, is inherently destructive.

Thanks
