### ISSUE TITLE
Config Keybind appearing cursed in control screen

### ISSUE THREAD

**Issue by VaporeonScripts** [quinn-semele/expanded-storage#23]
![image](https://github.com/user-attachments/assets/75beb258-ab6c-4ddc-97c6-e3f48e5e6b29)
(latest 1.21.1 version of the mod)

**Comment by quinn-semele** [comment]
Thanks for reporting, I'll get around to fixing that

**Comment by quinn-semele** [comment]
Released, only appeared to affect Fabric and Quilt releases. *Note the CurseForge releases might still be pending...*

---

**Expanded Storage 14.1.3** for **1.21**
- Fix config key translation on Fabric/Quilt.

CurseForge [Fabric](<https://curseforge.com/minecraft/mc-mods/expanded-storage/files/5664465>) | [Quilt](<https://curseforge.com/minecraft/mc-mods/expanded-storage/files/5664466>)
Modrinth [Fabric](<https://modrinth.com/mod/jCCPlP3c/version/Lk3QveWE>) | [Quilt](<https://modrinth.com/mod/jCCPlP3c/version/89mQcTAx>)
