### ISSUE TITLE
Menu type cant be changed?

### ISSUE THREAD

**Issue by asanaik** [quinn-semele/expanded-storage#29]
I had selected the option of having the storage inventory all be one screen which I didn't realize at first that would mean with diamond and netherite chest you cant see all of the chest, as there is no scroll option. And I cant seem to find a way to switch it to one of the other options I checked the config but there wasn't anything that seemed to work. ive added an example image of the diamond chest.
Also when I go out of fullscreen it then can be seen as show in the second image.

![image](https://github.com/user-attachments/assets/fe39947f-0717-4ef7-946f-2c29244b70b9)
![image](https://github.com/user-attachments/assets/e5bb4ee9-65d5-404a-9c91-102875423c68)

**Comment by quinn-semele** [comment]
You should be able to press `SHIFT+G` or go into the ingame mods list, find Expanded Storage, and access the screen type selection screen that way.

The single option does have edge cases like this where slots will appear off screen for some gui scales and monitor / window sizes.

Honestly need to think about reworking this as it seems to be a reoccuring issue...

**Comment by asanaik** [comment]
> o

omg thank you shift G worked, I couldn't find out how to do that anywhere, if anything just making that more clear would be good to.

**Comment by EtoKobato** [comment]
- mc 1.21
- fabric 0.16.5
- sodium
- sodium extra

GUI scale set to **2x**
screen 1920 x 1080 15.6 inch
if i set scale to **0(auto)** the ui works but is too large to play.

![image](https://github.com/user-attachments/assets/2abd0124-e712-49af-89b2-56e696ca8ec6)
![image](https://github.com/user-attachments/assets/a3c0ff8c-8854-424c-a7af-18b58e234679)
