### ISSUE TITLE
ES 7.3.8 Forge for MC 1.16.5 requires unavailable lib

### ISSUE THREAD

**Issue by purelydistinct** [quinn-semele/expanded-storage#32]
Expanded Storage 7.3.8 
Forge 36.2.42
MC 1.16.5 
ES requires ninjaphenix_container_lib 1.2.7 or above when it is no longer available. ES does not work without it

<img width="635" alt="{2D8871CA-8705-4C11-B504-F1FA8C5EF29E}" src="https://github.com/user-attachments/assets/784e8750-8531-40a5-9ca3-12b8818efa55">

**Comment by quinn-semele** [comment]
Thanks for reporting this, sadly unless I can hack something together this likely won't get resolved as I've long since stopped modding for 1.16.5, will see what I can hack together in 6 hours.

**Comment by purelydistinct** [comment]
I understand if you can’t do anything. Perhaps it might be worth removing from CurseForge if it doesn’t work? On Modrinth ES isn’t available for MC 1.16.5 so it’s only on CurseForge

**Comment by quinn-semele** [comment]
I'll do that real quick, sorry work has me so tired.
