### ISSUE TITLE
Chests have the wrong culling hitbox

### ISSUE THREAD

**Issue by Lolothepro** [quinn-semele/expanded-storage#36]
![2024-11-11_13 35 38](https://github.com/user-attachments/assets/7d9b96d1-8062-470a-8518-16cef5694dba)

**Comment by quinn-semele** [comment]
Can you let me know what you used to get that screenshot because I don't see anything wrong code-wise.

**Comment by Lolothepro** [comment]
You can use the command “/neoforge debug_blockentity_renderbounds true”.

![2024-11-16_08 47 20](https://github.com/user-attachments/assets/bf5ee739-7482-4c19-86b3-eb322f0d8759)

This is the default culling hitbox for chests

**Comment by quinn-semele** [comment]
I really cannot seeing this being an actual issue in practice, this neoforge/minecraftforge patch is at least 6 years old and unless my chests are disappearing when they should be in view, I can't see why enlarging the culling bounding box provides any benefit.

If you do find cases of the chests not rendering when they should, please report that instead.
