### ISSUE TITLE
NeoForge 1.21.3: Open chests are not rendered when the main part is not in the field of vision

### ISSUE THREAD

**Issue by Lolothepro** [quinn-semele/expanded-storage#37]
https://github.com/user-attachments/assets/af474492-5734-46b7-b840-eaf430347e6b

**Comment by quinn-semele** [comment]
I'm going to be frank, this is an absolute waste of time. But it'll be fixed properly.

**Comment by Lolothepro** [comment]
another example :

https://github.com/user-attachments/assets/583fc647-a387-4a39-8a83-60e12f9fb081

**Comment by quinn-semele** [comment]
Fixed in beta 5.
