### ISSUE TITLE
Will 1.20.1 forge support neoforge loader?

### ISSUE THREAD

**Issue by liangmoe** [quinn-semele/expanded-storage#4]
[main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'forge', Requested by: 'expandedstorage', Expected range: '[47.2,)', Actual version: '47.1.100'

**Comment by liangmoe** [comment]
There is no mod only works on neoforge afaik, asking here just bc the page has added the dependency for neo and neo is compatible for all the forge mod on 1.20.1
![image](https://github.com/quinn-semele/expanded-storage/assets/135343248/dfc2c8bb-1387-4b96-833d-b77c8caac438)

**Comment by quinn-semele** [comment]
Yeah I didn't realise neoforge didn't support 47.2.x, I'll push back the version number in a bit and test it works before releasing.

**Comment by quinn-semele** [comment]
Well this is a little worrying, my CF account seems to be gone?

**Comment by quinn-semele** [comment]
Alright, should all be working now, can download from:

https://legacy.curseforge.com/minecraft/mc-mods/expanded-storage/files/5145367
https://modrinth.com/mod/expanded-storage/version/R3M171FU
