### ISSUE TITLE
1.21.4 Port Progress

### ISSUE THREAD

**Issue by quinn-semele** [quinn-semele/expanded-storage#46]
~~Still need to write a special model renderer for chest minecarts.~~
Need to fix up datagens to make use of new renderers and item model conditions.

~~Would ideally want to convert our own chest models into it's own class so it can be used by the special renderer as well but currently just falling back on vanilla's model as we share the same texture format still.~~

**Comment by ellie-rose-garden** [comment]
Consider changing upgrade textures to be layered from and to models.
Look into why item models have a particle texture defined.

**Comment by quinn-semele** [comment]
Okay definitive todo list:
# Required
- [ ] Create item model definitions for barrels that also fix the waxed models.
- [ ] Create item model definitions for mini chests / barrels which makes use of the sparrow property and also fixes the waxed mini barrel models.
# Nice to haves
- [ ] Make chest upgrade models use 2 texture layers so that we can reduce the amount of textures needed and make it easier to add new upgrades / tiers in the future.
