### ISSUE TITLE
[fabric/1.21.4] Barrel Issue?

### ISSUE THREAD

**Issue by Thiana** [quinn-semele/expanded-storage#47]
There doesn't appear to be any way to open a gui for the barrels added by the mod. I'm not sure if that is intended behavior since hoppers do work with them . The chests work as expected.

Thanks.

**Comment by quinn-semele** [comment]
Thanks for the report, will look into it and get it fixed asap.

**Comment by quinn-semele** [comment]
Looks like I forgot to register the opening stats, easy fix 😅 

> **Expanded Storage 16.0.0-beta.2** for **1.21.4**
> - Fix not being able to open barrels, I forgot to register the opening stats.
> 
> A detailed changelog can be found [here](https://github.com/quinn-semele/expanded-storage/compare/16.0.0-beta.1+1.21.4...650eabc6c79b586a8d3d3d42a9b9b35f12a63a65).
> 
> :curseforge: [NeoForge](<https://curseforge.com/minecraft/mc-mods/expanded-storage/files/5970344>) | [Fabric](<https://curseforge.com/minecraft/mc-mods/expanded-storage/files/5970345>) | [Quilt](<https://curseforge.com/minecraft/mc-mods/expanded-storage/files/5970346>)
> :modrinth: [NeoForge](<https://modrinth.com/mod/jCCPlP3c/version/k5Baz6Ze>) | [Fabric](<https://modrinth.com/mod/jCCPlP3c/version/4sQntka6>) | [Quilt](<https://modrinth.com/mod/jCCPlP3c/version/DxUpvZJY>)
