### ISSUE TITLE
Merge Chest with itself possible (Fabric 16.0.0-beta.3)

### ISSUE THREAD

**Issue by audaki** [quinn-semele/expanded-storage#48]
It is possible to merge a chest with itself with the chest merger tool. I don’t know if it’s a big issue, but it confuses the player and visually the chest will look broken.

PS: thank you for the great mod!

**Comment by quinn-semele** [comment]
I recently fixed this in dev I believe, been doing a lot of refactors so it might be a little bit until a new release is out for 1.21.4

**Comment by quinn-semele** [comment]
As a side note, you can also merge chests that aren't adjecent meaning one will be glitched in the wrong type and the original one you've clicked won't change.

**Comment by quinn-semele** [comment]
Fixed in 16.0.0-beta.4
