### ISSUE TITLE
Extend from LidOpenable

### ISSUE THREAD

**Issue by audaki** [quinn-semele/expanded-storage#49]
Heya,

I’ve read in the other issue you’re rn in a big refactoring spree. Have you seen this comment about this mod? https://github.com/TimVincii/Terrastorage/issues/1#issuecomment-2367002314

> This issue affects all the chests in Expanded Storage, since they were all made from scratch and don't extend LidOpenable, but instead have their own ChestLidController.

Not sure if extending from LidOpenable is a viable thing to do, but it seems like it could improve compatibility with other mods.

rgds, Kira

**Comment by quinn-semele** [comment]
I wonder why I was never made aware of this issue before... I'll look into it, thank you.

**Comment by quinn-semele** [comment]
Looks extremely simple, consider it done.

**Comment by quinn-semele** [comment]
Fixed in 16.0.0-beta.4
