### ISSUE TITLE
Computercraft Peripherals broken

### ISSUE THREAD

**Issue by CoreBytee** [quinn-semele/expanded-storage#5]
Hi,

I'm using version v10.1.4 of the mod for minecraft 1.20.1 and i'm experiencing an issue with the computercraft integration.

I have this setup with a computer in my world.
![image](https://github.com/quinn-semele/expanded-storage/assets/62032154/a945531f-a98f-479b-901f-96757c16dc1e)

and if I type `peripherals` into the cc terminal I can see the connected chest (as expected)
![image](https://github.com/quinn-semele/expanded-storage/assets/62032154/b3350adf-b9b0-4087-97a9-ba4597cdce84)

this also works when I fill half of the chest
![image](https://github.com/quinn-semele/expanded-storage/assets/62032154/cb6b7d89-b8ec-42f9-bfdd-6955ec2bdd5d)
![image](https://github.com/quinn-semele/expanded-storage/assets/62032154/9109638d-d2d7-49f5-b793-432a90479973)

but stops working when I fully fill the chest.
![image](https://github.com/quinn-semele/expanded-storage/assets/62032154/a26e601f-3525-40ff-9438-6b07956fca7f)
![image](https://github.com/quinn-semele/expanded-storage/assets/62032154/7eeb5b48-01d7-4c47-a140-50f9256b84ee)

I think this is because if I fully fill the chest the data of the right part of the chest goes crazy (because it is the bottom half). And that also explains why filling the first half works.

Let me know if you need more information 🙂!

**Comment by quinn-semele** [comment]
I don't have any specific integration with computer craft but I'll see how easy it might be to add in the next week.

**Comment by quinn-semele** [comment]
Could you provide an older version number it did work it cause currently adding explicit support won't be happening due to the license of parts of their api: <https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.20.x/LICENSES/LicenseRef-CCPL.txt>

**Comment by quinn-semele** [comment]
Found an easy fix on my end, hopefully will have `10.3.0` out tomorrow.

**Comment by quinn-semele** [comment]
Fixed https://modrinth.com/mod/expanded-storage/version/10.3.0-beta.1+fabric
