### ISSUE TITLE
mod causes server-side crashes

### ISSUE THREAD

**Issue by PeakXing** [quinn-semele/expanded-storage#6]
[crash-2024-03-14_21.20.43-server.txt](https://github.com/quinn-semele/expanded-storage/files/14615094/crash-2024-03-14_21.20.43-server.txt)
At the time, the server crashed when printing with mechanically-powered cannons, as did the single-player game, and eventually I realized that I couldn't use the print function to print vertically-placed crates.

**Comment by quinn-semele** [comment]
Just thought I'd update this, I took a bit more of a break from modding than I had wanted but I have this fixed in development with better placement implemented too. 

Hopefully a release isn't too far off.

**Comment by quinn-semele** [comment]
Fixed: https://modrinth.com/mod/expanded-storage/version/10.3.0-beta.1+forge
