### ISSUE TITLE
Carry-On issue.

### ISSUE THREAD

**Issue by 8droid** [quinn-semele/expanded-storage#8]
You cannot put a carried chest to another chest to get a double chest.

**Comment by quinn-semele** [comment]
Fixed in dev for 1.20.1, will try and port to 1.20.4 soon after `10.3.0`'s release.

**Comment by quinn-semele** [comment]
Should be fixed in `12.1.0-beta.1`: https://modrinth.com/mod/expanded-storage/version/12.1.0-beta.1+fabric
